apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "8084"
  APP_ENV: "production"
  AUTH_SERVICE_URL: "http://auth:8081"
  PRODUCT_SERVICE_URL: "http://product:8082"
  INVENTORY_SERVICE_URL: "http://inventory:8083"
