apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.order.port }}"
  APP_ENV: "production"
  AUTH_SERVICE_URL: "http://auth:{{ .Values.auth.port }}"
  PRODUCT_SERVICE_URL: "http://product:{{ .Values.product.port }}"
  INVENTORY_SERVICE_URL: "http://inventory:{{ .Values.inventory.port }}"
