apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: {{ .Values.namespace }}
  labels:
    app: order

spec:
  replicas: {{ .Values.order.replicas }}

  selector:
    matchLabels:
      app: order

  template:
    metadata:
      labels:
        app: order

    spec:
      containers:
        - name: order
          image: ghcr.io/zyncc/order:latest
          imagePullPolicy: Always

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi

          ports:
            - containerPort: {{ .Values.order.port }}

          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.order.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.order.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
