apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: order
  ports:
    - port: {{ .Values.order.port }}
      targetPort: {{ .Values.order.port }}
  type: ClusterIP
