// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/product/pkg/types/proto/product.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDMessage) Reset() {
	*x = IDMessage{}
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDMessage) ProtoMessage() {}

func (x *IDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDMessage.ProtoReflect.Descriptor instead.
func (*IDMessage) Descriptor() ([]byte, []int) {
	return file_services_product_pkg_types_proto_product_proto_rawDescGZIP(), []int{0}
}

func (x *IDMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Inventory     *Inventory             `protobuf:"bytes,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_services_product_pkg_types_proto_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type Inventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Small         int32                  `protobuf:"varint,1,opt,name=small,proto3" json:"small,omitempty"`
	Medium        int32                  `protobuf:"varint,2,opt,name=medium,proto3" json:"medium,omitempty"`
	Large         int32                  `protobuf:"varint,3,opt,name=large,proto3" json:"large,omitempty"`
	ExtraLarge    int32                  `protobuf:"varint,4,opt,name=extra_large,json=extraLarge,proto3" json:"extra_large,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_services_product_pkg_types_proto_product_proto_rawDescGZIP(), []int{2}
}

func (x *Inventory) GetSmall() int32 {
	if x != nil {
		return x.Small
	}
	return 0
}

func (x *Inventory) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *Inventory) GetLarge() int32 {
	if x != nil {
		return x.Large
	}
	return 0
}

func (x *Inventory) GetExtraLarge() int32 {
	if x != nil {
		return x.ExtraLarge
	}
	return 0
}

type GetAllProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsRequest) Reset() {
	*x = GetAllProductsRequest{}
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsRequest) ProtoMessage() {}

func (x *GetAllProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsRequest.ProtoReflect.Descriptor instead.
func (*GetAllProductsRequest) Descriptor() ([]byte, []int) {
	return file_services_product_pkg_types_proto_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAllProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsResponse) Reset() {
	*x = GetAllProductsResponse{}
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsResponse) ProtoMessage() {}

func (x *GetAllProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsResponse.ProtoReflect.Descriptor instead.
func (*GetAllProductsResponse) Descriptor() ([]byte, []int) {
	return file_services_product_pkg_types_proto_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_services_product_pkg_types_proto_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_services_product_pkg_types_proto_product_proto_rawDescGZIP(), []int{5}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_services_product_pkg_types_proto_product_proto protoreflect.FileDescriptor

const file_services_product_pkg_types_proto_product_proto_rawDesc = "" +
	"\n" +
	".services/product/pkg/types/proto/product.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\tIDMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb2\x01\n" +
	"\x14CreateProductRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x120\n" +
	"\tinventory\x18\x05 \x01(\v2\x12.product.InventoryR\tinventory\"p\n" +
	"\tInventory\x12\x14\n" +
	"\x05small\x18\x01 \x01(\x05R\x05small\x12\x16\n" +
	"\x06medium\x18\x02 \x01(\x05R\x06medium\x12\x14\n" +
	"\x05large\x18\x03 \x01(\x05R\x05large\x12\x1f\n" +
	"\vextra_large\x18\x04 \x01(\x05R\n" +
	"extraLarge\"E\n" +
	"\x15GetAllProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"F\n" +
	"\x16GetAllProductsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\"\xf9\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xdf\x01\n" +
	"\x0eProductService\x12B\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x12.product.IDMessage\x12Q\n" +
	"\x0eGetAllProducts\x12\x1e.product.GetAllProductsRequest\x1a\x1f.product.GetAllProductsResponse\x126\n" +
	"\x0eGetProductByID\x12\x12.product.IDMessage\x1a\x10.product.ProductBJZHgithub.com/zyncc/ecommerce-microservice/services/product/pkg/types/protob\x06proto3"

var (
	file_services_product_pkg_types_proto_product_proto_rawDescOnce sync.Once
	file_services_product_pkg_types_proto_product_proto_rawDescData []byte
)

func file_services_product_pkg_types_proto_product_proto_rawDescGZIP() []byte {
	file_services_product_pkg_types_proto_product_proto_rawDescOnce.Do(func() {
		file_services_product_pkg_types_proto_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_product_pkg_types_proto_product_proto_rawDesc), len(file_services_product_pkg_types_proto_product_proto_rawDesc)))
	})
	return file_services_product_pkg_types_proto_product_proto_rawDescData
}

var file_services_product_pkg_types_proto_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_product_pkg_types_proto_product_proto_goTypes = []any{
	(*IDMessage)(nil),              // 0: product.IDMessage
	(*CreateProductRequest)(nil),   // 1: product.CreateProductRequest
	(*Inventory)(nil),              // 2: product.Inventory
	(*GetAllProductsRequest)(nil),  // 3: product.GetAllProductsRequest
	(*GetAllProductsResponse)(nil), // 4: product.GetAllProductsResponse
	(*Product)(nil),                // 5: product.Product
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_services_product_pkg_types_proto_product_proto_depIdxs = []int32{
	2, // 0: product.CreateProductRequest.inventory:type_name -> product.Inventory
	5, // 1: product.GetAllProductsResponse.products:type_name -> product.Product
	6, // 2: product.Product.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	3, // 5: product.ProductService.GetAllProducts:input_type -> product.GetAllProductsRequest
	0, // 6: product.ProductService.GetProductByID:input_type -> product.IDMessage
	0, // 7: product.ProductService.CreateProduct:output_type -> product.IDMessage
	4, // 8: product.ProductService.GetAllProducts:output_type -> product.GetAllProductsResponse
	5, // 9: product.ProductService.GetProductByID:output_type -> product.Product
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_product_pkg_types_proto_product_proto_init() }
func file_services_product_pkg_types_proto_product_proto_init() {
	if File_services_product_pkg_types_proto_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_product_pkg_types_proto_product_proto_rawDesc), len(file_services_product_pkg_types_proto_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_product_pkg_types_proto_product_proto_goTypes,
		DependencyIndexes: file_services_product_pkg_types_proto_product_proto_depIdxs,
		MessageInfos:      file_services_product_pkg_types_proto_product_proto_msgTypes,
	}.Build()
	File_services_product_pkg_types_proto_product_proto = out.File
	file_services_product_pkg_types_proto_product_proto_goTypes = nil
	file_services_product_pkg_types_proto_product_proto_depIdxs = nil
}
