apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: ecommerce-microservice
  labels:
    app: product
spec:
  template:
    metadata:
      labels:
        app: product
  selector:
    matchLabels:
      app: product
  replicas: 2
  spec:
    containers:
      - name: product
        image: ghcr.io/zyncc/product:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: product-config
          - secretRef:
              name: product-secret
        ports:
          - containerPort: 8082
    restartPolicy: Always
