apiVersion: v1
kind: Secret
metadata:
  name: inventory-secret
  namespace: ecommerce-microservice
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce_microservice
  JWT_SECRET: AScXcl9Zexof3LIqJZYwFjOQw1aqSAqL
  KAFKA_BROKER: kafka:9092
