apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ecommerce-microservice
data:
  PORT: "8080"
  APP_ENV: "production"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  PRODUCT_SERVICE_URL: "http://product-service:8082"
  INVENTORY_SERVICE_URL: "http://inventory-service:8083"
  ORDER_SERVICE_URL: "http://order-service:8084"
  PAYMENT_SERVICE_URL: "http://payment-service:8085"
  SHIPMENT_SERVICE_URL: "http://shipment-service:8086"
  REDIS_URL: "redis:6379"
