apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecommerce-microservice
  labels:
    app: api-gateway
spec:
  template:
    metadata:
      labels:
        app: api-gateway
  selector:
    matchLabels:
      app: api-gateway
  replicas: 2
  spec:
    containers:
      - name: api-gateway
        image: zync07/api-gateway:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: api-gateway-config
          - secretRef:
              name: api-gateway-secret
        ports:
          - containerPort: 8080
    restartPolicy: Always
