services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_microservice
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_microservice"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.8.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: confluentinc/cp-kafka:8.2.2
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "afc45394-d7ff-498b-8e0e-ab03f24ca7cc"

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    volumes:
      - kafka_kraft:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1",
        ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run /etc/alloy/config.alloy --server.http.listen-addr=0.0.0.0:12345
    depends_on:
      - loki
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - observability

  # api-gateway:
  #   build:
  #     context: .
  #     dockerfile: ./services/api-gateway/Dockerfile
  #   container_name: api-gateway
  #   env_file:
  #     - ./services/api-gateway/.env.docker
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     auth-service:
  #       condition: service_healthy
  #     product-service:
  #       condition: service_healthy
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  # auth-service:
  #   build:
  #     context: .
  #     dockerfile: ./services/auth/Dockerfile
  #   container_name: auth-service
  #   env_file:
  #     - ./services/auth/.env.docker
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  # product-service:
  #   build:
  #     context: .
  #     dockerfile: ./services/product/Dockerfile
  #   container_name: product-service
  #   env_file:
  #     - ./services/product/.env.docker
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8082/healthz"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  # inventory-service:
  #   build:
  #     context: .
  #     dockerfile: ./services/inventory/Dockerfile
  #   container_name: inventory-service
  #   env_file:
  #     - ./services/inventory/.env.docker
  #   ports:
  #     - "8083:8083"
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
  #     product-service:
  #       condition: service_healthy
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8083/healthz"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

volumes:
  kafka_kraft:
  postgres_data:
  loki_data:
  grafana_data:
  redis_data:

networks:
  observability:
    driver: bridge
