// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/auth/pkg/types/proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAddressesRequest) Reset() {
	*x = GetAllAddressesRequest{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAddressesRequest) ProtoMessage() {}

func (x *GetAllAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetAllAddressesRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllAddressesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllAddressesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Addresses     []*GetAddressByIDResponse `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAddressesResponse) Reset() {
	*x = GetAllAddressesResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAddressesResponse) ProtoMessage() {}

func (x *GetAllAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAddressesResponse.ProtoReflect.Descriptor instead.
func (*GetAllAddressesResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllAddressesResponse) GetAddresses() []*GetAddressByIDResponse {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GetAddressByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressByIDRequest) Reset() {
	*x = GetAddressByIDRequest{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByIDRequest) ProtoMessage() {}

func (x *GetAddressByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAddressByIDRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAddressByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Address1      string                 `protobuf:"bytes,7,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2      *string                `protobuf:"bytes,8,opt,name=address2,proto3,oneof" json:"address2,omitempty"`
	City          string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,11,opt,name=zip,proto3" json:"zip,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressByIDResponse) Reset() {
	*x = GetAddressByIDResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressByIDResponse) ProtoMessage() {}

func (x *GetAddressByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAddressByIDResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetAddressByIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAddressByIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAddressByIDResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetAddressByIDResponse) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *GetAddressByIDResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetAddressByIDResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetAddressByIDResponse) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *GetAddressByIDResponse) GetAddress2() string {
	if x != nil && x.Address2 != nil {
		return *x.Address2
	}
	return ""
}

func (x *GetAddressByIDResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetAddressByIDResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetAddressByIDResponse) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *GetAddressByIDResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetAddressByIDResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SignUpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *SignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *SignInResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SignInResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSessionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSessionResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetSessionResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetSessionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Address1      string                 `protobuf:"bytes,6,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2      *string                `protobuf:"bytes,7,opt,name=address2,proto3,oneof" json:"address2,omitempty"`
	City          string                 `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,10,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAddressRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAddressRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *CreateAddressRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAddressRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAddressRequest) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *CreateAddressRequest) GetAddress2() string {
	if x != nil && x.Address2 != nil {
		return *x.Address2
	}
	return ""
}

func (x *CreateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateAddressRequest) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type CreateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressResponse) Reset() {
	*x = CreateAddressResponse{}
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressResponse) ProtoMessage() {}

func (x *CreateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_auth_pkg_types_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *CreateAddressResponse) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

var File_services_auth_pkg_types_proto_auth_proto protoreflect.FileDescriptor

const file_services_auth_pkg_types_proto_auth_proto_rawDesc = "" +
	"\n" +
	"(services/auth/pkg/types/proto/auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\x16GetAllAddressesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"U\n" +
	"\x17GetAllAddressesResponse\x12:\n" +
	"\taddresses\x18\x01 \x03(\v2\x1c.auth.GetAddressByIDResponseR\taddresses\"'\n" +
	"\x15GetAddressByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb8\x03\n" +
	"\x16GetAddressByIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x1a\n" +
	"\baddress1\x18\a \x01(\tR\baddress1\x12\x1f\n" +
	"\baddress2\x18\b \x01(\tH\x01R\baddress2\x88\x01\x01\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\v \x01(\tR\x03zip\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_address2\"\x80\x01\n" +
	"\rSignUpRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x04 \x01(\tR\x0fconfirmPassword\" \n" +
	"\x0eSignUpResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\rSignInRequest\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"X\n" +
	"\x0eSignInResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x9d\x01\n" +
	"\x12GetSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"9\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xb0\x02\n" +
	"\x14CreateAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x00R\blastName\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1a\n" +
	"\baddress1\x18\x06 \x01(\tR\baddress1\x12\x1f\n" +
	"\baddress2\x18\a \x01(\tH\x01R\baddress2\x88\x01\x01\x12\x12\n" +
	"\x04city\x18\b \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\n" +
	" \x01(\tR\x03zipB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_address2\"6\n" +
	"\x15CreateAddressResponse\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId2\xe2\x03\n" +
	"\vAuthService\x123\n" +
	"\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x14.auth.SignUpResponse\x123\n" +
	"\x06SignIn\x12\x13.auth.SignInRequest\x1a\x14.auth.SignInResponse\x12>\n" +
	"\n" +
	"GetSession\x12\x16.google.protobuf.Empty\x1a\x18.auth.GetSessionResponse\x12B\n" +
	"\fRefreshToken\x12\x16.google.protobuf.Empty\x1a\x1a.auth.RefreshTokenResponse\x12H\n" +
	"\rCreateAddress\x12\x1a.auth.CreateAddressRequest\x1a\x1b.auth.CreateAddressResponse\x12K\n" +
	"\x0eGetAddressByID\x12\x1b.auth.GetAddressByIDRequest\x1a\x1c.auth.GetAddressByIDResponse\x12N\n" +
	"\x0fGetAllAddresses\x12\x1c.auth.GetAllAddressesRequest\x1a\x1d.auth.GetAllAddressesResponseBGZEgithub.com/zyncc/ecommerce-microservice/services/auth/pkg/types/protob\x06proto3"

var (
	file_services_auth_pkg_types_proto_auth_proto_rawDescOnce sync.Once
	file_services_auth_pkg_types_proto_auth_proto_rawDescData []byte
)

func file_services_auth_pkg_types_proto_auth_proto_rawDescGZIP() []byte {
	file_services_auth_pkg_types_proto_auth_proto_rawDescOnce.Do(func() {
		file_services_auth_pkg_types_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_auth_pkg_types_proto_auth_proto_rawDesc), len(file_services_auth_pkg_types_proto_auth_proto_rawDesc)))
	})
	return file_services_auth_pkg_types_proto_auth_proto_rawDescData
}

var file_services_auth_pkg_types_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_auth_pkg_types_proto_auth_proto_goTypes = []any{
	(*GetAllAddressesRequest)(nil),  // 0: auth.GetAllAddressesRequest
	(*GetAllAddressesResponse)(nil), // 1: auth.GetAllAddressesResponse
	(*GetAddressByIDRequest)(nil),   // 2: auth.GetAddressByIDRequest
	(*GetAddressByIDResponse)(nil),  // 3: auth.GetAddressByIDResponse
	(*SignUpRequest)(nil),           // 4: auth.SignUpRequest
	(*SignUpResponse)(nil),          // 5: auth.SignUpResponse
	(*SignInRequest)(nil),           // 6: auth.SignInRequest
	(*SignInResponse)(nil),          // 7: auth.SignInResponse
	(*GetSessionResponse)(nil),      // 8: auth.GetSessionResponse
	(*RefreshTokenResponse)(nil),    // 9: auth.RefreshTokenResponse
	(*CreateAddressRequest)(nil),    // 10: auth.CreateAddressRequest
	(*CreateAddressResponse)(nil),   // 11: auth.CreateAddressResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_services_auth_pkg_types_proto_auth_proto_depIdxs = []int32{
	3,  // 0: auth.GetAllAddressesResponse.addresses:type_name -> auth.GetAddressByIDResponse
	12, // 1: auth.GetAddressByIDResponse.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: auth.GetAddressByIDResponse.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: auth.GetSessionResponse.created_at:type_name -> google.protobuf.Timestamp
	4,  // 4: auth.AuthService.SignUp:input_type -> auth.SignUpRequest
	6,  // 5: auth.AuthService.SignIn:input_type -> auth.SignInRequest
	13, // 6: auth.AuthService.GetSession:input_type -> google.protobuf.Empty
	13, // 7: auth.AuthService.RefreshToken:input_type -> google.protobuf.Empty
	10, // 8: auth.AuthService.CreateAddress:input_type -> auth.CreateAddressRequest
	2,  // 9: auth.AuthService.GetAddressByID:input_type -> auth.GetAddressByIDRequest
	0,  // 10: auth.AuthService.GetAllAddresses:input_type -> auth.GetAllAddressesRequest
	5,  // 11: auth.AuthService.SignUp:output_type -> auth.SignUpResponse
	7,  // 12: auth.AuthService.SignIn:output_type -> auth.SignInResponse
	8,  // 13: auth.AuthService.GetSession:output_type -> auth.GetSessionResponse
	9,  // 14: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	11, // 15: auth.AuthService.CreateAddress:output_type -> auth.CreateAddressResponse
	3,  // 16: auth.AuthService.GetAddressByID:output_type -> auth.GetAddressByIDResponse
	1,  // 17: auth.AuthService.GetAllAddresses:output_type -> auth.GetAllAddressesResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_auth_pkg_types_proto_auth_proto_init() }
func file_services_auth_pkg_types_proto_auth_proto_init() {
	if File_services_auth_pkg_types_proto_auth_proto != nil {
		return
	}
	file_services_auth_pkg_types_proto_auth_proto_msgTypes[3].OneofWrappers = []any{}
	file_services_auth_pkg_types_proto_auth_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_auth_pkg_types_proto_auth_proto_rawDesc), len(file_services_auth_pkg_types_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_auth_pkg_types_proto_auth_proto_goTypes,
		DependencyIndexes: file_services_auth_pkg_types_proto_auth_proto_depIdxs,
		MessageInfos:      file_services_auth_pkg_types_proto_auth_proto_msgTypes,
	}.Build()
	File_services_auth_pkg_types_proto_auth_proto = out.File
	file_services_auth_pkg_types_proto_auth_proto_goTypes = nil
	file_services_auth_pkg_types_proto_auth_proto_depIdxs = nil
}
