apiVersion: v1
kind: Secret
metadata:
  name: shipping-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce_microservice
  KAFKA_BROKER: kafka:9092
