apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: shipping
  ports:
    - port: {{ .Values.shipping.port }}
      targetPort: {{ .Values.shipping.port }}
  type: ClusterIP
