apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: ecommerce-microservice
  labels:
    app: notification
spec:
  template:
    metadata:
      labels:
        app: notification
  selector:
    matchLabels:
      app: notification
  replicas: 2
  spec:
    containers:
      - name: notification
        image: ghcr.io/zyncc/notification:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: notification-config
          - secretRef:
              name: notification-secret
    restartPolicy: Always
