apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: ecommerce-microservice
type: Opaque
stringData:
  KAFKA_BROKER: kafka:9092
  FROM_EMAIL: chandankrishna288@gmail.com
  FROM_EMAIL_SMTP: smtp.gmail.com
  SMTP_ADDR: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_PASSWORD: "dnyr auip rawa jfvi"
