// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/order/pkg/types/proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDMessage) Reset() {
	*x = IDMessage{}
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDMessage) ProtoMessage() {}

func (x *IDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDMessage.ProtoReflect.Descriptor instead.
func (*IDMessage) Descriptor() ([]byte, []int) {
	return file_services_order_pkg_types_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *IDMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	OrderTotal    float64                `protobuf:"fixed64,4,opt,name=order_total,json=orderTotal,proto3" json:"order_total,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	FirstName     string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	Address_1     string                 `protobuf:"bytes,10,opt,name=address_1,json=address1,proto3" json:"address_1,omitempty"`
	Address_2     *string                `protobuf:"bytes,11,opt,name=address_2,json=address2,proto3,oneof" json:"address_2,omitempty"`
	City          string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,14,opt,name=zip,proto3" json:"zip,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OrderItems    []*OrderItems          `protobuf:"bytes,17,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_services_order_pkg_types_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Order) GetOrderTotal() float64 {
	if x != nil {
		return x.OrderTotal
	}
	return 0
}

func (x *Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *Order) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Order) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *Order) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Order) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Order) GetAddress_1() string {
	if x != nil {
		return x.Address_1
	}
	return ""
}

func (x *Order) GetAddress_2() string {
	if x != nil && x.Address_2 != nil {
		return *x.Address_2
	}
	return ""
}

func (x *Order) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Order) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Order) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetOrderItems() []*OrderItems {
	if x != nil {
		return x.OrderItems
	}
	return nil
}

type OrderItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Size          string                 `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItems) Reset() {
	*x = OrderItems{}
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItems) ProtoMessage() {}

func (x *OrderItems) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItems.ProtoReflect.Descriptor instead.
func (*OrderItems) Descriptor() ([]byte, []int) {
	return file_services_order_pkg_types_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItems) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderItems) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItems) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItems) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItems) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *OrderItems) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItems) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderItems) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_services_order_pkg_types_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_order_pkg_types_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_services_order_pkg_types_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_services_order_pkg_types_proto_order_proto protoreflect.FileDescriptor

const file_services_order_pkg_types_proto_order_proto_rawDesc = "" +
	"\n" +
	"*services/order/pkg/types/proto/order.proto\x12\x05order\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\tIDMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbe\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x01R\bsubtotal\x12\x1f\n" +
	"\vorder_total\x18\x04 \x01(\x01R\n" +
	"orderTotal\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12 \n" +
	"\tlast_name\x18\a \x01(\tH\x00R\blastName\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12\x1b\n" +
	"\taddress_1\x18\n" +
	" \x01(\tR\baddress1\x12 \n" +
	"\taddress_2\x18\v \x01(\tH\x01R\baddress2\x88\x01\x01\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\r \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x0e \x01(\tR\x03zip\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\vorder_items\x18\x11 \x03(\v2\x11.order.OrderItemsR\n" +
	"orderItemsB\f\n" +
	"\n" +
	"_last_nameB\f\n" +
	"\n" +
	"_address_2\"\x92\x02\n" +
	"\n" +
	"OrderItems\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04size\x18\x05 \x01(\tR\x04size\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"t\n" +
	"\x12CreateOrderRequest\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.order.OrderItemR\x05items\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\"p\n" +
	"\tOrderItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price2{\n" +
	"\fOrderService\x12:\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x10.order.IDMessage\x12/\n" +
	"\rFindOrderByID\x12\x10.order.IDMessage\x1a\f.order.OrderBHZFgithub.com/zyncc/ecommerce-microservice/services/order/pkg/types/protob\x06proto3"

var (
	file_services_order_pkg_types_proto_order_proto_rawDescOnce sync.Once
	file_services_order_pkg_types_proto_order_proto_rawDescData []byte
)

func file_services_order_pkg_types_proto_order_proto_rawDescGZIP() []byte {
	file_services_order_pkg_types_proto_order_proto_rawDescOnce.Do(func() {
		file_services_order_pkg_types_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_order_pkg_types_proto_order_proto_rawDesc), len(file_services_order_pkg_types_proto_order_proto_rawDesc)))
	})
	return file_services_order_pkg_types_proto_order_proto_rawDescData
}

var file_services_order_pkg_types_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_services_order_pkg_types_proto_order_proto_goTypes = []any{
	(*IDMessage)(nil),             // 0: order.IDMessage
	(*Order)(nil),                 // 1: order.Order
	(*OrderItems)(nil),            // 2: order.OrderItems
	(*CreateOrderRequest)(nil),    // 3: order.CreateOrderRequest
	(*OrderItem)(nil),             // 4: order.OrderItem
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_services_order_pkg_types_proto_order_proto_depIdxs = []int32{
	5, // 0: order.Order.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: order.Order.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: order.Order.order_items:type_name -> order.OrderItems
	5, // 3: order.OrderItems.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: order.OrderItems.updated_at:type_name -> google.protobuf.Timestamp
	4, // 5: order.CreateOrderRequest.items:type_name -> order.OrderItem
	3, // 6: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	0, // 7: order.OrderService.FindOrderByID:input_type -> order.IDMessage
	0, // 8: order.OrderService.CreateOrder:output_type -> order.IDMessage
	1, // 9: order.OrderService.FindOrderByID:output_type -> order.Order
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_services_order_pkg_types_proto_order_proto_init() }
func file_services_order_pkg_types_proto_order_proto_init() {
	if File_services_order_pkg_types_proto_order_proto != nil {
		return
	}
	file_services_order_pkg_types_proto_order_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_order_pkg_types_proto_order_proto_rawDesc), len(file_services_order_pkg_types_proto_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_order_pkg_types_proto_order_proto_goTypes,
		DependencyIndexes: file_services_order_pkg_types_proto_order_proto_depIdxs,
		MessageInfos:      file_services_order_pkg_types_proto_order_proto_msgTypes,
	}.Build()
	File_services_order_pkg_types_proto_order_proto = out.File
	file_services_order_pkg_types_proto_order_proto_goTypes = nil
	file_services_order_pkg_types_proto_order_proto_depIdxs = nil
}
