apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ecommerce_microservice
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce_microservice?sslmode=disable
