apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: payment
  ports:
    - port: {{ .Values.payment.port }}
      targetPort: {{ .Values.payment.port }}
  type: ClusterIP
