CREATE TABLE IF NOT EXISTS shipments (
  id UUID PRIMARY KEY,
  order_id UUID NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,

  status TEXT NOT NULL DEFAULT 'AWAITING_PICKUP',
  carrier TEXT NOT NULL,
  tracking_number UUID UNIQUE NOT NULL,

  shipped_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
