apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: ecommerce-microservice
  labels:
    app: order
spec:
  template:
    metadata:
      labels:
        app: order
  selector:
    matchLabels:
      app: order
  replicas: 2
  spec:
    containers:
      - name: order
        image: ghcr.io/zyncc/order:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8084
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: order-config
          - secretRef:
              name: order-secret
        ports:
          - containerPort: 8084
    restartPolicy: Always
