apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce-microservice
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: ecommerce_microservice
