apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: ecommerce-microservice
  labels:
    app: shipping
spec:
  template:
    metadata:
      labels:
        app: shipping
  selector:
    matchLabels:
      app: shipping
  replicas: 2
  spec:
    containers:
      - name: shipping
        image: ghcr.io/zyncc/shipping:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8086
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: shipping-config
          - secretRef:
              name: shipping-secret
        ports:
          - containerPort: 8086
    restartPolicy: Always
