apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ecommerce-microservice

spec:
  clusterIP: None

  selector:
    app: kafka

  ports:
    - name: broker
      port: 9092
      targetPort: 9092

    - name: controller
      port: 9093
      targetPort: 9093

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: ecommerce-microservice

spec:
  serviceName: kafka

  replicas: 1

  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka

    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:8.2.2
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 9092
              name: broker

            - containerPort: 9093
              name: controller

          envFrom:
            - configMapRef:
                name: kafka-config

          resources:
            requests:
              cpu: 500m
              memory: 512Mi

            limits:
              cpu: "1"
              memory: 1Gi

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

          readinessProbe:
            exec:
              command:
                - kafka-broker-api-versions
                - --bootstrap-server
                - localhost:9092
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            exec:
              command:
                - kafka-broker-api-versions
                - --bootstrap-server
                - localhost:9092
            initialDelaySeconds: 30
            periodSeconds: 20

  volumeClaimTemplates:
    - metadata:
        name: kafka-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 2Gi
