apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Values.namespace }}
  labels:
    app: auth

spec:
  replicas: {{ .Values.auth.replicas }}

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
        - name: auth
          image: ghcr.io/zyncc/auth:latest
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi

          ports:
            - containerPort: {{ .Values.auth.port }}

          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.auth.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.auth.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
