apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: product
  ports:
    - port: {{ .Values.product.port }}
      targetPort: {{ .Values.product.port }}
  type: ClusterIP
