// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/payment/pkg/types/proto/payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebhookRequest) Reset() {
	*x = WebhookRequest{}
	mi := &file_services_payment_pkg_types_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookRequest) ProtoMessage() {}

func (x *WebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payment_pkg_types_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookRequest.ProtoReflect.Descriptor instead.
func (*WebhookRequest) Descriptor() ([]byte, []int) {
	return file_services_payment_pkg_types_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *WebhookRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WebhookRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WebhookRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *WebhookRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WebhookRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_services_payment_pkg_types_proto_payment_proto protoreflect.FileDescriptor

const file_services_payment_pkg_types_proto_payment_proto_rawDesc = "" +
	"\n" +
	".services/payment/pkg/types/proto/payment.proto\x12\apayment\x1a\x1bgoogle/protobuf/empty.proto\"\xc7\x01\n" +
	"\x0eWebhookRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency2S\n" +
	"\x0ePaymentService\x12A\n" +
	"\x0ePaymentWebhook\x12\x17.payment.WebhookRequest\x1a\x16.google.protobuf.EmptyBJZHgithub.com/zyncc/ecommerce-microservice/services/payment/pkg/types/protob\x06proto3"

var (
	file_services_payment_pkg_types_proto_payment_proto_rawDescOnce sync.Once
	file_services_payment_pkg_types_proto_payment_proto_rawDescData []byte
)

func file_services_payment_pkg_types_proto_payment_proto_rawDescGZIP() []byte {
	file_services_payment_pkg_types_proto_payment_proto_rawDescOnce.Do(func() {
		file_services_payment_pkg_types_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_payment_pkg_types_proto_payment_proto_rawDesc), len(file_services_payment_pkg_types_proto_payment_proto_rawDesc)))
	})
	return file_services_payment_pkg_types_proto_payment_proto_rawDescData
}

var file_services_payment_pkg_types_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_services_payment_pkg_types_proto_payment_proto_goTypes = []any{
	(*WebhookRequest)(nil), // 0: payment.WebhookRequest
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_services_payment_pkg_types_proto_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.PaymentWebhook:input_type -> payment.WebhookRequest
	1, // 1: payment.PaymentService.PaymentWebhook:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_payment_pkg_types_proto_payment_proto_init() }
func file_services_payment_pkg_types_proto_payment_proto_init() {
	if File_services_payment_pkg_types_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_payment_pkg_types_proto_payment_proto_rawDesc), len(file_services_payment_pkg_types_proto_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_payment_pkg_types_proto_payment_proto_goTypes,
		DependencyIndexes: file_services_payment_pkg_types_proto_payment_proto_depIdxs,
		MessageInfos:      file_services_payment_pkg_types_proto_payment_proto_msgTypes,
	}.Build()
	File_services_payment_pkg_types_proto_payment_proto = out.File
	file_services_payment_pkg_types_proto_payment_proto_goTypes = nil
	file_services_payment_pkg_types_proto_payment_proto_depIdxs = nil
}
