// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/shipping/pkg/types/proto/shipment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDMessage) Reset() {
	*x = IDMessage{}
	mi := &file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDMessage) ProtoMessage() {}

func (x *IDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDMessage.ProtoReflect.Descriptor instead.
func (*IDMessage) Descriptor() ([]byte, []int) {
	return file_services_shipping_pkg_types_proto_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *IDMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WebhookRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebhookRequest) Reset() {
	*x = WebhookRequest{}
	mi := &file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookRequest) ProtoMessage() {}

func (x *WebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookRequest.ProtoReflect.Descriptor instead.
func (*WebhookRequest) Descriptor() ([]byte, []int) {
	return file_services_shipping_pkg_types_proto_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *WebhookRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *WebhookRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Shipment struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	IdempotencyKey *string                `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Carrier        string                 `protobuf:"bytes,5,opt,name=carrier,proto3" json:"carrier,omitempty"`
	ShippingCost   float64                `protobuf:"fixed64,6,opt,name=shipping_cost,json=shippingCost,proto3" json:"shipping_cost,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,7,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	ShippedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=shipped_at,json=shippedAt,proto3,oneof" json:"shipped_at,omitempty"`
	DeliveredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=delivered_at,json=deliveredAt,proto3,oneof" json:"delivered_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_services_shipping_pkg_types_proto_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Shipment) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *Shipment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Shipment) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *Shipment) GetShippingCost() float64 {
	if x != nil {
		return x.ShippingCost
	}
	return 0
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetShippedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ShippedAt
	}
	return nil
}

func (x *Shipment) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_services_shipping_pkg_types_proto_shipment_proto protoreflect.FileDescriptor

const file_services_shipping_pkg_types_proto_shipment_proto_rawDesc = "" +
	"\n" +
	"0services/shipping/pkg/types/proto/shipment.proto\x12\bshipping\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n" +
	"\tIDMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"z\n" +
	"\x0eWebhookRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x91\x04\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12,\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\acarrier\x18\x05 \x01(\tR\acarrier\x12#\n" +
	"\rshipping_cost\x18\x06 \x01(\x01R\fshippingCost\x12'\n" +
	"\x0ftracking_number\x18\a \x01(\tR\x0etrackingNumber\x12>\n" +
	"\n" +
	"shipped_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tshippedAt\x88\x01\x01\x12B\n" +
	"\fdelivered_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vdeliveredAt\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x12\n" +
	"\x10_idempotency_keyB\r\n" +
	"\v_shipped_atB\x0f\n" +
	"\r_delivered_at2\x9a\x01\n" +
	"\x0fShippingService\x12C\n" +
	"\x0fShipmentWebhook\x12\x18.shipping.WebhookRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x17GetShipmentByTrackingID\x12\x13.shipping.IDMessage\x1a\x12.shipping.ShipmentBKZIgithub.com/zyncc/ecommerce-microservice/services/shipping/pkg/types/protob\x06proto3"

var (
	file_services_shipping_pkg_types_proto_shipment_proto_rawDescOnce sync.Once
	file_services_shipping_pkg_types_proto_shipment_proto_rawDescData []byte
)

func file_services_shipping_pkg_types_proto_shipment_proto_rawDescGZIP() []byte {
	file_services_shipping_pkg_types_proto_shipment_proto_rawDescOnce.Do(func() {
		file_services_shipping_pkg_types_proto_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_shipping_pkg_types_proto_shipment_proto_rawDesc), len(file_services_shipping_pkg_types_proto_shipment_proto_rawDesc)))
	})
	return file_services_shipping_pkg_types_proto_shipment_proto_rawDescData
}

var file_services_shipping_pkg_types_proto_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_shipping_pkg_types_proto_shipment_proto_goTypes = []any{
	(*IDMessage)(nil),             // 0: shipping.IDMessage
	(*WebhookRequest)(nil),        // 1: shipping.WebhookRequest
	(*Shipment)(nil),              // 2: shipping.Shipment
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_services_shipping_pkg_types_proto_shipment_proto_depIdxs = []int32{
	3, // 0: shipping.Shipment.shipped_at:type_name -> google.protobuf.Timestamp
	3, // 1: shipping.Shipment.delivered_at:type_name -> google.protobuf.Timestamp
	3, // 2: shipping.Shipment.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: shipping.Shipment.updated_at:type_name -> google.protobuf.Timestamp
	1, // 4: shipping.ShippingService.ShipmentWebhook:input_type -> shipping.WebhookRequest
	0, // 5: shipping.ShippingService.GetShipmentByTrackingID:input_type -> shipping.IDMessage
	4, // 6: shipping.ShippingService.ShipmentWebhook:output_type -> google.protobuf.Empty
	2, // 7: shipping.ShippingService.GetShipmentByTrackingID:output_type -> shipping.Shipment
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_services_shipping_pkg_types_proto_shipment_proto_init() }
func file_services_shipping_pkg_types_proto_shipment_proto_init() {
	if File_services_shipping_pkg_types_proto_shipment_proto != nil {
		return
	}
	file_services_shipping_pkg_types_proto_shipment_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_shipping_pkg_types_proto_shipment_proto_rawDesc), len(file_services_shipping_pkg_types_proto_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_shipping_pkg_types_proto_shipment_proto_goTypes,
		DependencyIndexes: file_services_shipping_pkg_types_proto_shipment_proto_depIdxs,
		MessageInfos:      file_services_shipping_pkg_types_proto_shipment_proto_msgTypes,
	}.Build()
	File_services_shipping_pkg_types_proto_shipment_proto = out.File
	file_services_shipping_pkg_types_proto_shipment_proto_goTypes = nil
	file_services_shipping_pkg_types_proto_shipment_proto_depIdxs = nil
}
