apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: ecommerce-microservice
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce_microservice
  KAFKA_BROKER: kafka:9092
  REDIS_URL: redis:6379
