apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.apiGateway.port }}"
  APP_ENV: "production"
  AUTH_SERVICE_URL: "http://auth:{{ .Values.auth.port }}"
  PRODUCT_SERVICE_URL: "http://product:{{ .Values.product.port }}"
  INVENTORY_SERVICE_URL: "http://inventory:{{ .Values.inventory.port }}"
  ORDER_SERVICE_URL: "http://order:{{ .Values.order.port }}"
  PAYMENT_SERVICE_URL: "http://payment:{{ .Values.payment.port }}"
  SHIPMENT_SERVICE_URL: "http://shipping:{{ .Values.shipping.port }}"
  REDIS_URL: "redis:6379"
