apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres-postgresql.db:5432/ecommerce_microservice
  KAFKA_BROKER: kafka.confluent:9092
  REDIS_URL: redis:6379
