apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: inventory
  ports:
    - port: {{ .Values.inventory.port }}
      targetPort: {{ .Values.inventory.port }}
  type: ClusterIP
