apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  KAFKA_BROKER: kafka.confluent:9092
  FROM_EMAIL:
  FROM_EMAIL_SMTP:
  SMTP_ADDR:
  SMTP_PORT:
  SMTP_PASSWORD:
