apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  serviceName: kafka
  replicas: 1

  selector:
    matchLabels:
      app: kafka

  template:
    metadata:
      labels:
        app: kafka

    spec:
      hostname: kafka-0
      subdomain: kafka

      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          imagePullPolicy: IfNotPresent

          ports:
            - name: broker
              containerPort: 9092

            - name: controller
              containerPort: 9093

          envFrom:
            - configMapRef:
                name: kafka-config

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(POD_NAME).kafka:9092

          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

          # startupProbe:
          #   exec:
          #     command:
          #       - kafka-broker-api-versions
          #       - --bootstrap-server
          #       - localhost:9092
          #   failureThreshold: 30
          #   periodSeconds: 10

          # readinessProbe:
          #   exec:
          #     command:
          #       - kafka-broker-api-versions
          #       - --bootstrap-server
          #       - localhost:9092
          #   initialDelaySeconds: 10
          #   periodSeconds: 10

          # livenessProbe:
          #   exec:
          #     command:
          #       - kafka-broker-api-versions
          #       - --bootstrap-server
          #       - localhost:9092
          #   initialDelaySeconds: 30
          #   periodSeconds: 20

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.kafka.storage }}
