apiVersion: batch/v1
kind: Job
metadata:
  name: database-migrations
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: migrate
          image: ghcr.io/zyncc/migrations:latest
          envFrom:
            - secretRef:
                name: postgres-secret

          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

              migrate \
                -path /migrations \
                -database "$DATABASE_URL" \
                up
