// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: services/inventory/pkg/types/proto/inventory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDMessage) Reset() {
	*x = IDMessage{}
	mi := &file_services_inventory_pkg_types_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDMessage) ProtoMessage() {}

func (x *IDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_inventory_pkg_types_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDMessage.ProtoReflect.Descriptor instead.
func (*IDMessage) Descriptor() ([]byte, []int) {
	return file_services_inventory_pkg_types_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *IDMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Small         int32                  `protobuf:"varint,3,opt,name=small,proto3" json:"small,omitempty"`
	Medium        int32                  `protobuf:"varint,4,opt,name=medium,proto3" json:"medium,omitempty"`
	Large         int32                  `protobuf:"varint,5,opt,name=large,proto3" json:"large,omitempty"`
	ExtraLarge    int32                  `protobuf:"varint,6,opt,name=extra_large,json=extraLarge,proto3" json:"extra_large,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_services_inventory_pkg_types_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_inventory_pkg_types_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_services_inventory_pkg_types_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetInventoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInventoryResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetInventoryResponse) GetSmall() int32 {
	if x != nil {
		return x.Small
	}
	return 0
}

func (x *GetInventoryResponse) GetMedium() int32 {
	if x != nil {
		return x.Medium
	}
	return 0
}

func (x *GetInventoryResponse) GetLarge() int32 {
	if x != nil {
		return x.Large
	}
	return 0
}

func (x *GetInventoryResponse) GetExtraLarge() int32 {
	if x != nil {
		return x.ExtraLarge
	}
	return 0
}

func (x *GetInventoryResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetInventoryResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_services_inventory_pkg_types_proto_inventory_proto protoreflect.FileDescriptor

const file_services_inventory_pkg_types_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"2services/inventory/pkg/types/proto/inventory.proto\x12\tinventory\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n" +
	"\tIDMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa0\x02\n" +
	"\x14GetInventoryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x14\n" +
	"\x05small\x18\x03 \x01(\x05R\x05small\x12\x16\n" +
	"\x06medium\x18\x04 \x01(\x05R\x06medium\x12\x14\n" +
	"\x05large\x18\x05 \x01(\x05R\x05large\x12\x1f\n" +
	"\vextra_large\x18\x06 \x01(\x05R\n" +
	"extraLarge\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2d\n" +
	"\x10InventoryService\x12P\n" +
	"\x17GetInventoryByProductID\x12\x14.inventory.IDMessage\x1a\x1f.inventory.GetInventoryResponseBLZJgithub.com/zyncc/ecommerce-microservice/services/inventory/pkg/types/protob\x06proto3"

var (
	file_services_inventory_pkg_types_proto_inventory_proto_rawDescOnce sync.Once
	file_services_inventory_pkg_types_proto_inventory_proto_rawDescData []byte
)

func file_services_inventory_pkg_types_proto_inventory_proto_rawDescGZIP() []byte {
	file_services_inventory_pkg_types_proto_inventory_proto_rawDescOnce.Do(func() {
		file_services_inventory_pkg_types_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_inventory_pkg_types_proto_inventory_proto_rawDesc), len(file_services_inventory_pkg_types_proto_inventory_proto_rawDesc)))
	})
	return file_services_inventory_pkg_types_proto_inventory_proto_rawDescData
}

var file_services_inventory_pkg_types_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_inventory_pkg_types_proto_inventory_proto_goTypes = []any{
	(*IDMessage)(nil),             // 0: inventory.IDMessage
	(*GetInventoryResponse)(nil),  // 1: inventory.GetInventoryResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_services_inventory_pkg_types_proto_inventory_proto_depIdxs = []int32{
	2, // 0: inventory.GetInventoryResponse.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: inventory.GetInventoryResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: inventory.InventoryService.GetInventoryByProductID:input_type -> inventory.IDMessage
	1, // 3: inventory.InventoryService.GetInventoryByProductID:output_type -> inventory.GetInventoryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_inventory_pkg_types_proto_inventory_proto_init() }
func file_services_inventory_pkg_types_proto_inventory_proto_init() {
	if File_services_inventory_pkg_types_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_inventory_pkg_types_proto_inventory_proto_rawDesc), len(file_services_inventory_pkg_types_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_inventory_pkg_types_proto_inventory_proto_goTypes,
		DependencyIndexes: file_services_inventory_pkg_types_proto_inventory_proto_depIdxs,
		MessageInfos:      file_services_inventory_pkg_types_proto_inventory_proto_msgTypes,
	}.Build()
	File_services_inventory_pkg_types_proto_inventory_proto = out.File
	file_services_inventory_pkg_types_proto_inventory_proto_goTypes = nil
	file_services_inventory_pkg_types_proto_inventory_proto_depIdxs = nil
}
