apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "8080"
  APP_ENV: "production"
  AUTH_SERVICE_URL: "http://auth:8081"
  PRODUCT_SERVICE_URL: "http://product:8082"
  INVENTORY_SERVICE_URL: "http://inventory:8083"
  ORDER_SERVICE_URL: "http://order:8084"
  PAYMENT_SERVICE_URL: "http://payment:8085"
  SHIPMENT_SERVICE_URL: "http://shipment:8086"
  REDIS_URL: "redis:6379"
