apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app: api-gateway

spec:
  replicas: {{ .Values.apiGateway.replicas }}

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      restartPolicy: Always

      containers:
        - name: api-gateway
          image: ghcr.io/zyncc/api-gateway:latest
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 2000m
              memory: 2000Mi

          ports:
            - containerPort: {{ .Values.apiGateway.port }}

          envFrom:
            - configMapRef:
                name: api-gateway-config
            - secretRef:
                name: api-gateway-secret

          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.apiGateway.port }}
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.apiGateway.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
